### ISSUE TITLE
Error 403 di testing notification Midtrans

### ISSUE THREAD

**Issue by dodeagung** [harrypujianto/Veritrans-Codeigniter#1]
Dear Pak Harry,

Terima kasih sudah mendevelop koneksi codeigniter dengan Midtrans,

Saya ingin bertanya sedikit, kenapa ya ketika saya masukkan link notification listener di Test notification callback Sandbox Midtrans, keluar error 403 yah?

saya coba mencari2 solusinya, agak frustasi sedikit karena keterangan error yang diberikan oleh midtrans sangat sedikit.

Mohon pencerahnnya pak.

Salam,
Agung

**Comment by harrypujianto** [comment]
ada screenshot gak pak?
hmm.. testing notifnya dari transaksi, atau testing pake demo yang ada di dashboard midtrans?

**Comment by denmaz** [comment]
saya juga dapat error, kalo saya lihat.. masalahnya di
$json_result = file_get_contents('php://input');
$result = json_decode($json_result);

$result => tidak menghasilkan object 
$result = json_decode($json_result, true); => tidak menghasilkan array 
apa bila di akses key dari kedua file tersebut menghasilkan nilai kosong.

ada sarang pak?
