### ISSUE TITLE
Tentang Support CodeIgniter

### ISSUE THREAD

**Issue by jepicode** [harrypujianto/Veritrans-Codeigniter#2]
Saya ingin mengintegrasikan midtrans ke website saya, kebetulan account bank midtrans saya belum di approve, jadi masih make sandbox. Untuk penggunaan sandbox itu kita menggunakan file yang mana yah? snap atau VT-web yah? dan beda kedua itu apa yah?

dan lagi dibagian snap documentation itu kita bisa memilih untuk meng-enable pembayaran yang mana saja, saya sudah coba membuat array baru, dan memasukannya ke variable $transaction_data, tapi kenapa tetap semua pilihan ada yah?

**Comment by harrypujianto** [comment]
Silahkan bapak menggunakan snap. VT-Web merupakan versi sebelumnya dari snap, dimana customer akan di redirect ke halaman pembayaran midtrans. SNAP akan membuka halaman pembayaran di website anda, sehingga tidak ada redirection. Tetapi, response charge snap ada juga dalam bentuk link pembayaran, sehingga, anda juga bisa meredirect customer ke halaman pembayaran midtrans dengan snap. 

untuk informasi lebih detail silahkan lihat dokumentasi  https://snap-docs.midtrans.com/
