### ISSUE TITLE
Pengutran kostumisasi va_number bca_va

### ISSUE THREAD

**Issue by jepicode** [harrypujianto/Veritrans-Codeigniter#3]
Hallo,

saya sedikit membutuhkan bantuan untuk integrasi codeigniter, saya ingi nmerubah va_number bca_va saya, tapi kenapa tidak bisa ya? tidak berhasil. berikut code nya :
```
$transaction_data = array(
'transaction_details'=> $transaction_details,
'item_details'       => $item_details,
'enabled_payments'   => array("bca_va"),
'customer_details'   => $customer_details,
'credit_card'        => $credit_card,
'bca_va'             => array("va_number" => "12345678910"),
'expiry'             => $custom_expiry,
);
```

**Comment by harrypujianto** [comment]
hallo,

boleh diperjelas pak, tidak bisa seperti apa? tidak dapat response? atau dapat response tetapi error?

**Comment by jepicode** [comment]
hallo pak harry,

mungkin saya agak sedikit bingung atau bagaimana dengan sistem pembayaran midtrans.
jadi jika pembeli ingin membayar produk, nomor virtual account / account number yang terkait akan selalu ditentukan oleh midtrans, atau kita sebagai developer bisa mengatur virtual account itu sendiri?

**Comment by harrypujianto** [comment]
Yang bisa pake custom va number hanya yang open amount pak. Kalo yang default di setnya closed amount. Closed amount itu misal harga 100K, harus dibayar 100K. nomor closed amount di generate oleh midtrans.

**Comment by desta88** [comment]
> 
> 
> Yang bisa pake custom va number hanya yang open amount pak. Kalo yang default di setnya closed amount. Closed amount itu misal harga 100K, harus dibayar 100K. nomor closed amount di generate oleh midtrans.

**Open Amount** maksudnya apa ya? Apakah itu termasuk dari  parameter 'enabled_payments'?
