### ISSUE TITLE
Notifikasi Pembayaran

### ISSUE THREAD

**Issue by jepicode** [harrypujianto/Veritrans-Codeigniter#4]
Hallo pak Harry,

maaf saya membuka topik baru lagi, karena topik yang berbeda.
disini saya ingin bertanya bagaimana sistem midtrans memberi tahukan jika pembayaran sudah dilakukan? apakah kita membuat sebuah halaman yang setiap detiknya akan mengecek status dari setiap order dan menyimpan di database, atau bagaimana?

saya membaca dokumentasi, jika midtrans mengirimkan notifikasi ke website (link yang ada di pengaturan), tapi bagaimana halaman tersebut bisa mengetahui adanya data yang dikirim oleh midtrans? apakah harus melakukan pengecekan terus menerus?

**Comment by harrypujianto** [comment]
Jadi midtrans akan mengirimkan notifikasi untuk setiap transaksi. Ketika transaksi dicreate maupun setelah transaksi dibayar. Notifikasi dari Midtrans ada 2. 1 email notif, 1 lagi HTTP POST notif. Http post notif ini otomatis diterima pak sama server bapak. JIka pake librari ci bisa diliat di [notif controller](https://github.com/harrypujianto/Veritrans-Codeigniter/blob/master/application/controllers/notification.php). Di code itu notif akan diterima dan di proses. Jadi bapak tidak perlu melakukan get status terus menerus ke midtrans. Semoga dapat dipahami pak. Silahkan dicoba dahulu codenya

**Comment by jepicode** [comment]
Maaf pak sebelumnya saya agak kurang mengerti.
pertama saya sudah download repository ini dan saya pindahkan ke web saya. bapak bisa akses di https://pinopi.com, yang artinya controller notif ada di https://pinopi.com/notification.
kedua, saya coba membuat order, dan saya lakukan pembayaran di sandbox, lalu saya buka https://pinopi.com/notification, tapi tidak keluar hasil apapun. apa ada pengaturan lainnya? selain mengganti server key?
ketiga, saya bingung di `file_get_contents('php://input')`, saya tau kalo file tersebut akan menangkap post dari midtrans jika ada notif, tapi bagaimana website saya bisa tau kalo sedang ada yg dikirim atau diterima?

**Comment by harrypujianto** [comment]
Link notif url ini memang bukan untuk dibuka di browser, karena belum tentu notif sampai setelah browser berhasil di load. bisa saja sebelum slsai di load notif sudah sampai. maka dari itu, silahkan tulis hasil notif ke dalam log (error_log) contoh paling simpelnya.

**Comment by fajaruddinmeilana** [comment]
Hallo Pak Harry,
Saya juga mengalami case yang sama, saya masih kurang paham dengan notification yg diberikan dari midtrans seperti apa untuk saya mengetahui customer sudah bayar selain mendapat notification melaui email? agar saya dapat mengupdate datanya ke database. 

dan 1 lagi yg saya mau tanyakan, saya menggunakan metode SNAP dari midtrans. dan untuk **gross_amount**nya itu kalau tidak salah harus sesuai dengan harga subtotal itemnya ya ? saya sudah mencoba memasukan nilai **gross_amount** yg tidak sesuai dengan subtotal itemnya, namun program  nya tidak jalan. yg saya mau saya tanyakan disini adalah bagaiman jika dalam sistem saya ada potongan diskon voucher ? @harrypujianto 
![image](https://user-images.githubusercontent.com/36482562/36216482-8ee8a7fe-11e1-11e8-9f63-711b9f5049f2.png)

**Comment by harrypujianto** [comment]
https://github.com/harrypujianto/Veritrans-Codeigniter/blob/master/application/controllers/notification.php#L42
dibaris itu ada code untuk mencatat notifikasi yang masuk kedalam error log. silahkan cek error log anda. jika sudah ada notifkasi dalam bentuk json yang masuk, maka endpoint sudah berjalan dengan baik. kemudian silahkan uncomment baris-baris dibawahnya.

Snap hanya terima gross amount dengna nilai yang sama dengna nilai total dari item_details->price * item_details->qty. untuk promo, silahkan ubah nilai harga menjadi nilai negative. misalnya -200000.

**Comment by fajaruddinmeilana** [comment]
Hallo Pak Harry,
Saya masih kurang mengerti untuk notificationnya. setelah saya coba apa yg pak harry jelaskan di atas namun saya tidak mendapatkan data json apapun setelah terjadi perubahan status pada dashboard sanbox saya?
![image](https://user-images.githubusercontent.com/36482562/36243710-8b972336-1255-11e8-93e9-7aed5965b992.png)
![image](https://user-images.githubusercontent.com/36482562/36243721-a3ab9aba-1255-11e8-8c6b-2783b7c5f5bf.png)
![image](https://user-images.githubusercontent.com/36482562/36243752-c223b644-1255-11e8-9451-6d02b551b9f9.png)
![image](https://user-images.githubusercontent.com/36482562/36243782-e6d18b92-1255-11e8-8f9a-3d6084ba62f2.png)

**Comment by fajaruddinmeilana** [comment]
Ow ow ow.... ternyata oh ternyata
![image](https://user-images.githubusercontent.com/36482562/36244283-30d6b6de-1258-11e8-9fb6-9448e5ec0528.png)

Terimakasih atas bantuannya Pak Harry

**Comment by yudigopels** [comment]
mohon info, saya ada error 
ERROR - 2018-06-23 22:22:39 --> The session cookie data did not match what was expected. This could be a possible hacking attempt.
session aplikasi posisi diarahkan ke  database session bukan difile, akhirnya tdk dpt menerima http notifikasi

mohon bantuan dan terima kasih

**Comment by kartono21** [comment]
Hi Mas Harry,

ini di controller saya saat ini

$result = $request->input('data');
$data = json_decode($result, true);
$transaction = $data['transaction_status'];

ketika saya echo $transaction, di dashboard midtrans muncul internal server error..tapi pas saya postman muncul hasil echonya.

Sama ketika saya mau update data, saya dapat internal server error terus.

itu kendalanya dimana yah pak?

**Comment by fixxay** [comment]
Halo Mas Harry

mau tanya, kalo mau ambil data untuk gross amount, ngambil darimananya ya?
![image](https://user-images.githubusercontent.com/55292495/64881071-06d28d80-d684-11e9-82f3-0bdde2a64acf.png)
