### ISSUE TITLE
Order Id

### ISSUE THREAD

**Issue by jepicode** [harrypujianto/Veritrans-Codeigniter#5]
Hallo pak,
saya ingin bertanya, kan order id bisa melambangkan transaction id, sedangkan untuk mendapatkan transaction id saya harus menginsert di database, baru saya mendapatkan id untuk order id. tetapi jika saya menginsert data tersebut, masih ada kemungkinan pembeli meng-close pop up midtrans sehingga data tersebut tidak digunakan. bagaimana ya kejelasannya?

**Comment by harrypujianto** [comment]
Transaction ID merupakan identifier internal midtrans. didapatkan setelah transaksi selesai apapun hasil transaksinya. maka dari itu, silahkan menggunakan order id sebagai identifier antara midtrans dan system anda.
