### ISSUE TITLE
checkout_snap submit

### ISSUE THREAD

**Issue by fajaruddinmeilana** [harrypujianto/Veritrans-Codeigniter#6]
Hallo Pak Harry,
Bisa pandu saya untuk mengirim data dari form checkout_snapnya?
![image](https://user-images.githubusercontent.com/36482562/36263159-19982482-129c-11e8-85c6-c6bbb55d1f6a.png)

maaf saya masih agak bingung untuk mengirimkan datanya. Terimakasih

**Comment by fixxay** [comment]
Sama, saya msh bingung form nya
