### ISSUE TITLE
Penambahan Item voucvcher & ongkir

### ISSUE THREAD

**Issue by fajaruddinmeilana** [harrypujianto/Veritrans-Codeigniter#7]
Hallo pak Harry,  
Maaf ya saya lagi yang nanya... Hehe. 
Pak klo saya tambahin item voucher + ongkir di item detail ada masalah ga ya? gross amountnya sesuai

**Comment by harrypujianto** [comment]
silahkan dijadikan item baru. tambahkan item details lagi. 
untuk voucher gunakan nilai negatif. Untuk item_name mohon disesuaikan.

**Comment by fajaruddinmeilana** [comment]
Terimakasih Pak Harry
