### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by ruruberry** [harrypujianto/Veritrans-Codeigniter#8]
Permisi Pak Harry, kenapa ya saya tidak bisa get file ger content di notification.

$json_result = file_get_contents('php://input');
$result = json_decode($json_result);

dibagian ini saya tidak mendapatkan hasil atau jsonnya berisi kosong. Bagaimana cara saya mengatasi nya?

**Comment by harrypujianto** [comment]
hmm.. maaf atas keterlambatan membalas. 
mohon di cek
1. ketika di hit notification, apakah return 200. bisa menggunakan postman untuk test hit notif manual. 
2. pastikan url tersebut dapat di akses
3. apakah anda membuka notifikasi URL di browser? jika iya, tidak disarankan untuk melakukan ini.

**Comment by fajaruddinmeilana** [comment]
**SNAP WEB METODE PEMBAYARAN INTERNET BANKING**

Hallo Pak Harry, 

Bagaimana untuk menyimpan data kedalam database hasil dari inputan form dibawah ini jika menggunakan metode pembayaran internet banking:

**form action="site_url('snap/finish')"**

kalau di sistem yang saya buat itu penyimpanan data kedalam database terletak di **class snap/finish()**, kalau untuk metode pembayaran yg lain tidak ada masalah, namun jika menggunakan testing dengan metode pembayaran internet banking akan di direct ke halaman banknya masing2 untuk melakukan pembayaran dan setelah sukses melakukan pembayaran akan dikembalikan lagi ke halaman finish url website kita yang sudah kita seting di dashboard midtrans. 

Saya arahkan finish url tersebut ke **class snap/finish()** itu untuk melakukan penyimpanan data, namun data yg diterima itu tidak ada / atau kosong. hanya ada data transaksi pada error_log saja.

Nah saya kebingunan untuk melakukan penyimpanan data pembeli itu gimana jika menggunakan motode pembayaran internet banking.

Mohon solusinya pak harry. Terimakasih

Salam Hangat,
Fajar
