### ISSUE TITLE
Snap | Penyimpanan Data Pembeli Metode Internet Banking

### ISSUE THREAD

**Issue by fajaruddinmeilana** [harrypujianto/Veritrans-Codeigniter#9]
Hallo Pak Harry,

Bagaimana untuk menyimpan data kedalam database hasil dari inputan form dibawah ini jika menggunakan metode pembayaran internet banking:

**form action="site_url('snap/finish')"**

kalau di sistem yang saya buat itu penyimpanan data kedalam database terletak di **class snap/finish()**, kalau untuk metode pembayaran yg lain tidak ada masalah, namun jika menggunakan testing dengan metode pembayaran internet banking akan di direct ke halaman banknya masing2 untuk melakukan pembayaran dan setelah sukses melakukan pembayaran akan dikembalikan lagi ke halaman **finish url website kita** yang sudah kita seting di dashboard midtrans.

Saya arahkan **finish url tersebut ke class snap/finish()** itu untuk melakukan penyimpanan data, namun data yg diterima itu tidak ada / atau kosong. hanya ada data transaksi pada error_log saja.

Nah saya kebingunan untuk melakukan penyimpanan data pembeli itu gimana jika menggunakan motode pembayaran internet banking.

Mohon solusinya pak harry. Terimakasih

Salam Hangat,
Fajar

**Comment by harrypujianto** [comment]
untuk direct debit payment agak berbeda cara penanganannya. Saya share artikel untuk menghandle response tersebut

https://support.midtrans.com/hc/id/articles/360006156833-Petunjuk-Pembuatan-Landing-Page-untuk-Pembayaran-Direct-Debit

silahkan dipahami terlebih dahulu.

**Comment by fajaruddinmeilana** [comment]
Baik pak Harry saya coba pahami terlebih dahulu. sebelumnya terimakasih ya pak atas jawabannya

**Comment by fajaruddinmeilana** [comment]
Pagi pak Harry,

Saya sudah coba baca artikel yg pak harry kasih kemarin.
apakah response & query string get yg dikirim setelah kembali kehalaman website saya berlaku pada mode sandbox atau hanya berlaku di mode production aja ?

karena url yang saya dapatkan ketika mencoba dengan metode **bca klikpay** dan ketika kembali ke halaman website saya hanya seperti ini : 
https://pureheals.co.id/cdl/veritrans/snap/debist_finish?id=822fedb3-7415-454f-b0ca-c806b3a1e104

Salam hangat,
Fajar

**Comment by harrypujianto** [comment]
untuk bca klikpay akan ditambahkan query string id. 
ini link artikel yang membahas soal landing page bca klikpay pak.
https://support.midtrans.com/hc/en-us/articles/115004580573-BCA-KlikPay-Landing-Page-Development-Guideline

bca klikpay ini memang berbeda dengan direct debit lainnya. jadi memang harus di custom.

**Comment by fajaruddinmeilana** [comment]
baik pak untuk bcaklikpay data transaksi telah saya dapatkan,
namun untuk mendapatkan informasi pengiriman dan data pembeli lainnya dari form dibawah ini:

form id="payment-form" class="payment-form" method="post" action="=site_url('veritrans/snap/finish')"
input type="text" name="name" id="name" value=""
input type="text" name="phone" id="phone" value=""
input type="text" name="address" id="address" value=""
form` 

ini didapatkannya gimana ya pak? sedangkan saya membuat proses penyimpanan data order ke database pada method **class snap/finish()**

Kalau menggunakan metode pembayaran yg lainnya kan form tersebut di submit karna menggunakan ajax tersebut:
`snap.pay(data, {    
		                onSuccess: function(result){
		                    changeResult('success', result);
		                    console.log(result.status_message);
		                    console.log(result);
		                    $("#payment-form").submit();
		                },

Nah kalau menggunakan direct debit/ bca klikpay itu untuk melakukan penyimpanan datanya gimana pak ? saya menggunakan mode sandbox

Mohon solusinya pak. terimakasih

**Comment by fajaruddinmeilana** [comment]
Satu lagi pak yang ingin saya tanyakan,
untuk metode go-pay apakah ada demo scan untuk versi dekstop?
dan untuk yang versi mobile apakah setelah direct ke halaman **pay** akan direct ke halaman website kita lagi untuk mendapatkan response data ?

Mohon bantuannya pak harry. terimakasih

**Comment by harrypujianto** [comment]
Sample hanya untuk get token snap dan membuka pop up. 
untuk populate data customer dan data yang dibeli bisa dilakukan ditahap sebelumnya. 
atau 
proses pembukaan token snap dengan snap.pay() bisa dilakukan di tahap berikutnya. desain flow dapat disesuaikan, dan tidak harus mengikuti di repo ini. repo ini hanya sampel saja untuk buka token snap.

Nah kalau menggunakan direct debit/ bca klikpay itu untuk melakukan penyimpanan datanya gimana pak ? saya menggunakan mode sandbox
--> caranya ada di link ini. hanya ini caranya untuk mendapat response. Response ya pak bukan HTTP POST NOTIF.
cara simpanya gimana? gimana membedakan dengan pembyaran snap menggunakan kartu kredit yang langsung ke snap/finish?

bisa dicoba dengan if else statement yang sederhana

```
if($_GET['id']){
//untuk bca klikpay
json_decode($_GET['id'])
}else if($_POST['response']){
//untuk direct debit
json_decode($_POST['response'])
}
else{
//untuk yang cc/mandiri clikcpay
}
```


[direct debit](https://support.midtrans.com/hc/id/articles/360006156833-Petunjuk-Pembuatan-Landing-Page-untuk-Pembayaran-Direct-Debit)
[bca klikpay](https://support.midtrans.com/hc/en-us/articles/115004580573-BCA-KlikPay-Landing-Page-Development-Guideline)


tidak ada applikasi sandbox untuk gopay. Midtrans hanya menyediakan simulator 
[docs.midtrans.com](https://docs.midtrans.com/en/reference/test.html)
ada di tab `e-wallet`

**Comment by fajaruddinmeilana** [comment]
cara simpanya gimana? 
gimana membedakan dengan pembyaran snap menggunakan kartu kredit yang langsung ke snap/finish?
-> Penyimpanan ada di class **snap/finish**, sebelum muncul popup snap kan customer harus mengisi form seperti alamat pengirim, nama penerima dll. data dari form tersebut akan disubmit menggunkan ajax **snap.pay(data,{$("#payment-form").submit();}**  dan melakukan penyimpanan data di **snap/finish()**. 
->Nah yang membedakan direct debit dan bcaklikpay dari yang metode yang lain adalah: 
ketika customer memilih metode pembayaran tersebut customer akan langsung di direct ke situs banknya, sehinggal form pada point 1 tersbut tidak tersubmit sehingga pada **class snap/finish()** tidak mendapatkan hasil dari form tersebut hanya mendapatkan data transaksinya saja.

**Comment by harrypujianto** [comment]
Checkout bisa dibuat jadi beberapa tahap. 
jadi bisa ditahap pertama mengumpulkan data transaksi, data pelanggan, kemudian memunculkan snap

**Comment by fajaruddinmeilana** [comment]
Baik pak akan saya coba.

Pak untuk dapatkan response data untuk go-pay yang versi mobile responsivenya gimana ya ? soalnya saya tes setelah selesai melakukan pembayaran tidak dikembalikan lagi ke halaman website saya.

Mohon bantuannya pak. Terimakasih
